# Generated by Django 5.1.5 on 2025-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
            ],
        ),
    ]
