# Generated by Django 5.1.5 on 2025-01-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_headertouch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/banner_photos/')),
                ('title', models.CharField(max_length=100)),
                ('title_continue', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=350)),
                ('last', models.CharField(max_length=100)),
            ],
        ),
    ]
