# Generated by Django 5.1.5 on 2025-02-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='logo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(max_length=100),
        ),
    ]
