# Generated by Django 5.1.5 on 2025-02-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_header_logo_alter_menu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
