# Generated by Django 5.1.5 on 2025-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_about_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['menu'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(max_length=100, verbose_name='Название пункта меню'),
        ),
    ]
