# Generated by Django 5.1.5 on 2025-02-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_menu_options_remove_menu_url_alter_menu_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='touch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/touch_photos/'),
        ),
    ]
