# Generated by Django 5.1.5 on 2025-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_about_image_alter_client_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blog_media/slider_photos/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blog_media/client_photos/'),
        ),
        migrations.AlterField(
            model_name='guard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blog_media/guard_photos/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blog_media/banner_photos/'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blog_media/touch_photos/'),
        ),
    ]
