# Generated by Django 5.1.5 on 2025-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
