# Generated by Django 5.1.5 on 2025-02-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_menu_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(choices=[('home', 'Home'), ('service', 'Service'), ('guard', 'Guard'), ('contact', 'Contact'), ('about', 'About')], max_length=100, unique=True),
        ),
    ]
