# Generated by Django 5.1.5 on 2025-02-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_menu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(blank=True, choices=[('HOME', 'HOME'), ('SERVICES', 'SERVICES'), ('GUARDS', 'GUARDS'), ('CONTACT US', 'CONTACT US'), ('ABOUT', 'ABOUT')], max_length=100),
        ),
    ]
