# Generated by Django 5.1.5 on 2025-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_menu_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(max_length=100),
        ),
    ]
