# Generated by Django 5.1.5 on 2025-02-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_remove_menu_is_active_alter_menu_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(choices=[('HOME', 'HOME'), ('SERVICES', 'SERVICES'), ('GUARDS', 'GUARDS'), ('CONTACT US', 'CONTACT US'), ('ABOUT', 'ABOUT')], max_length=100, unique=True),
        ),
    ]
