# Generated by Django 5.1.5 on 2025-02-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_menu_is_active_alter_menu_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
