# Generated by Django 5.1.5 on 2025-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin_manager', 'Admin Manager'), ('moderator', 'Moderator'), ('editor', 'Editor'), ('support', 'Support'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
