# Generated by Django 5.1.5 on 2025-02-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=10),
        ),
    ]
