# Generated by Django 5.1.5 on 2025-02-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_usercontact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
