# Generated by Django 5.1.5 on 2025-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_usercontact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_tables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
