# Generated by Django 5.1.5 on 2025-02-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_customuser_allowed_tables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin_manager', 'Admin Manager'), ('moderator', 'Moderator'), ('editor', 'Editor'), ('support', 'Support'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
