# Generated by Django 5.1.5 on 2025-02-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_usercontact_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='status',
        ),
    ]
