# Generated by Django 5.1.5 on 2025-02-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_remove_usercontact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
