# Generated by Django 5.1.5 on 2025-02-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_remove_usercontact_read_usercontact_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='created_at',
        ),
    ]
